### ISSUE TITLE
Calculate, and plot, the probability of selecting the RSF best option at each trial

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#2]
- Create a plot showing the proportion of participants that select the risk sensitive foraging (RSF) best option on each trial.
- Compare this to a plot showing the probability of selecting the high EV option

This could answer Rui's question: Are people more likely to select the RSF option as they get closer to the goal?

**Comment by mdsteiner** [comment]
I added 02_issue2.R to solve this. The thing is that there is virtually no difference between RSF, high EV and high sample mean strategies, because they so seldom make differing predictions. Predictions tend to be more accurate for the high EV is low variance conditions (1 and 3).


![grafik](https://cloud.githubusercontent.com/assets/26483702/24454327/bd77e5fc-148b-11e7-9b6e-b42b1a5ffb9c.png)

**Comment by mdsteiner** [comment]
oops, just found a bug. There actually are differences:
Most of the time EV maximization strategy has the best proportion correct prediction values.
Interestingly, near trial 50 prediction accuracy goes down in all conditions for all models.

![grafik](https://cloud.githubusercontent.com/assets/26483702/24461749/63f4afc6-14a2-11e7-89fd-b88389c0bbc9.png)
